### ISSUE TITLE
Navbar bootstrap 4

### ISSUE THREAD

**Issue by phillipnunes** [karasube/scss-bs-navbar-mixin#1]
Hi,

Do you have plans to create a navbar mixin to Bootstrap 4 too?

Regards.

**Comment by uwgmk** [comment]
Nope. I don't use bootstrap anymore so this is unlikely to happen anytime soon.

This shouldn't be too difficult to do or time consuming to maintain so I encourage you to try to make it happen. Use https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss as a reference and replace values with customizable parameters.
